deployment:
  name: nginxapp-deploy   
  labels:
    app: nginxapp-deploy 
    version: v1
  selectorLabels:
    app: nginxapp-pod
    version: v1
  replicas: 1
  strategyType: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0
  nodeSelector:
    cloud.google.com/gke-nodepool: gkeappspool    
  containers:
  - name: nginx-app
    image: "<repo-name>/nginx:latest"
    imagePullPolicy: IfNotPresent
    memoryRequest: "250Mi"
    cpuRequest: "100m"
    memoryLimit: "500Mi"
    cpuLimit: "200m"
    containerPorts: [80]
service:
  name: nginxapp-svc
  selector:
    app: nginxapp-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80  
    
    
