deployment:
  name: visionapp-deploy
  serviceAccount: vertexai-sa
  labels:
    app: visionapp-deploy 
    version: v1
  selectorLabels:
    app: visionapp-pod
    version: v1
  replicas: 1
  strategyType: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0
  nodeSelector:
    cloud.google.com/gke-nodepool: gkeappspool
  containers:
  - name: vision-app
    image: "<repo-name>/visionlib2:v1.0"
    imagePullPolicy: Always
    memoryRequest: "250Mi"
    cpuRequest: "100m"
    memoryLimit: "500Mi"
    cpuLimit: "200m"
    containerPorts: [6062]
    envVars:
    - name: VISION_DIR_PATH
      value: /data   
    - name: PROJECT_ID
      value: apps-project-3108449
service:
  name: visionapp-svc
  selector:
    app: visionapp-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 6062  