deployment:
  name: vectorsearchapp-deploy
  serviceAccount: vertexai-sa
  labels:
    app: vectorsearchapp-deploy 
    version: v1
  selectorLabels:
    app: vectorsearchapp-pod
    version: v1
  replicas: 1
  strategyType: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0
  nodeSelector:
    cloud.google.com/gke-nodepool: gkeappspool
  containers:
  - name: vectorsearch-app
    image: "<repo-name>/vector-searchlib2:v1.0"
    imagePullPolicy: Always
    memoryRequest: "500Mi"
    cpuRequest: "500m"
    memoryLimit: "1Gi"
    cpuLimit: "1"
    containerPorts: [6064]
    envVars:
    - name: VECTOR_SEARCH_LOCATION
      value: us-central1    
    - name: PROJECT_ID
      value: apps-project-3108449
service:
  name: vectorsearchapp-svc
  selector:
    app: vectorsearchapp-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 6064  