deployment:
  name: retailgenieapp-deploy
  serviceAccount: vertexai-sa
  labels:
    app: retailgenieapp-deploy 
    version: v1
  selectorLabels:
    app: retailgenieapp-pod
    version: v1
  replicas: 1
  strategyType: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0
  nodeSelector:
    cloud.google.com/gke-nodepool: gkeappspool
  containers:
  - name: retailgenie-app
    image: "<repo-name>/retailgenie2:v1.0"
    imagePullPolicy: Always
    memoryRequest: "1Gi"
    cpuRequest: "500m"
    memoryLimit: "2Gi"
    cpuLimit: "1"
    containerPorts: [6067]
    envVars:
    - name: STORAGELIB_HOST
      value: http://storageapp-svc.vertexai.svc
    - name: SPEECHLIB_HOST
      value: http://speechapp-svc.vertexai.svc
    - name: TRANSLATELIB_HOST
      value: http://translateapp-svc.vertexai.svc
    - name: GENAI_TEXTLIB_HOST
      value: http://genaitextapp-svc.vertexai.svc
    - name: VISIONLIB_HOST
      value: http://visionapp-svc.vertexai.svc
    - name: GENAI_IMAGELIB_HOST
      value: http://genaiimageapp-svc.vertexai.svc
    - name: GENAI_VECTORSEARCHLIB_HOST
      value: http://vectorsearchapp-svc.vertexai.svc
    - name: PROJECT_ID
      value: apps-project-3108449
service:
  name: retailgenieapp-svc
  selector:
    app: retailgenieapp-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 6067