apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: pod-monitor
  namespace: smoke
spec:
  selector:
    matchLabels:
      mon: apacheapp-pod
  endpoints:
  - port: metrics    
    interval: 30s
