deployment:
  name: streamerclientapp-deploy
  serviceAccount: vertexai-sa
  labels:
    app: streamerclientapp-deploy 
    version: v1
  selectorLabels:
    app: streamerclientapp-pod
    version: v1
  replicas: 1
  strategyType: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0
  nodeSelector:
    cloud.google.com/gke-nodepool: gkeappspool
  containers:
  - name: streamerclient-app
    image: "<repo-name>/cloud-native-apps-repo/streamer-clientlib:v1.0"
    imagePullPolicy: Always
    memoryRequest: "500Mi"
    cpuRequest: "500m"
    memoryLimit: "1Gi"
    cpuLimit: "1"
    containerPorts: [8083]
    envVars:
    - name: WEBSOCK_STREAMER_HTTP_HOST
      value: http://streamerserverapp-svc.vertexai.svc
    - name: PROJECT_ID
      value: <project_id>    
service:
  name: streamerclientapp-svc
  selector:
    app: streamerclientapp-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8083  