deployment:
  name: vectorsearchapp-deploy
  serviceAccount: vertexai-sa
  labels:
    app: vectorsearchapp-deploy 
    version: v1
  selectorLabels:
    app: vectorsearchapp-pod
    version: v1
  replicas: 1
  strategyType: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0
  nodeSelector:
    cloud.google.com/gke-nodepool: gkeappspool
  containers:
  - name: vectorsearch-app
    image: "<repo-name>/cloud-native-apps-repo/vector-searchlib:v1.0"
    imagePullPolicy: Always
    memoryRequest: "500Mi"
    cpuRequest: "500m"
    memoryLimit: "1Gi"
    cpuLimit: "1"
    containerPorts: [6064]
    envVars:
    - name: VECTOR_SEARCH_LOCATION
      value: us-central1
    - name: VECTOR_SEARCH_TEXT_EMBEDDING_MODEL
      value: text-embedding-005
    - name: VECTOR_SEARCH_IMAGE_EMBEDDING_MODEL
      value: multimodalembedding@001
    - name: VECTOR_SEARCH_MULTILINGUAL_EMBEDDING_MODEL
      value: text-multilingual-embedding-002
    - name: PROJECT_ID
      value: <project_id>
service:
  name: vectorsearchapp-svc
  selector:
    app: vectorsearchapp-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 6064  